name: Detect Manifest Version Changes
# This workflow requires a PAT_TOKEN secret to be set in the repository
# The token needs 'repo' scope to trigger the publish workflow

on:
  push:
    branches:
      - master  # Adjust this to your default branch if different
    paths:
      - 'src/jsMain/resources/manifest.json'  # Only trigger on manifest.json changes

jobs:
  check-version-change:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  # We need at least the current and previous commit

      - name: Check for version change
        id: check_version
        run: |
          # Get the current manifest.json content
          CURRENT_VERSION=$(grep -o '"version": "[^"]*"' src/jsMain/resources/manifest.json | cut -d'"' -f4)
          echo "Current version: $CURRENT_VERSION"

          # Get the previous manifest.json content
          git checkout HEAD~1 src/jsMain/resources/manifest.json
          PREVIOUS_VERSION=$(grep -o '"version": "[^"]*"' src/jsMain/resources/manifest.json | cut -d'"' -f4)
          echo "Previous version: $PREVIOUS_VERSION"

          # Restore the current version of the file
          git checkout HEAD src/jsMain/resources/manifest.json

          # Compare versions
          if [ "$CURRENT_VERSION" != "$PREVIOUS_VERSION" ]; then
            echo "Version changed from $PREVIOUS_VERSION to $CURRENT_VERSION"
            echo "version_changed=true" >> $GITHUB_OUTPUT
          else
            echo "Version unchanged"
            echo "version_changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Trigger publish workflow
        if: steps.check_version.outputs.version_changed == 'true'
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}  # Personal Access Token with repo scope
          event-type: manifest-version-changed
          repository: theapache64/super-github
